// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Returns list of products",
            "schema": {
              "$ref": "#/definitions/ProductListBody"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns product by id",
            "schema": {
              "$ref": "#/definitions/ProductBody"
            }
          },
          "404": {
            "description": "Product is not found",
            "schema": {
              "$ref": "#/definitions/ErrorBody"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorBody"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ProductListBody": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "ProductListBody.products.[]"
          },
          "title": "ProductListBody.products",
          "type": "array"
        }
      },
      "required": [
        "products"
      ],
      "additionalProperties": false,
      "title": "ProductListBody",
      "type": "object"
    },
    "ProductBody": {
      "properties": {
        "product": {
          "$ref": "#/definitions/Product",
          "title": "ProductBody.product"
        }
      },
      "required": [
        "product"
      ],
      "additionalProperties": false,
      "title": "ProductBody",
      "type": "object"
    },
    "ErrorBody": {
      "properties": {
        "message": {
          "title": "ErrorBody.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "ErrorBody",
      "type": "object"
    },
    "Product": {
      "properties": {
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};